# Generated by Django 5.1.1 on 2026-06-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_cliente_fluxocaixa_remove_roupa_numero_roupa_tamanho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
