# Generated by Django 5.1.1 on 2026-06-22 20:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_alter_cliente_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagamento',
            old_name='valor_pago',
            new_name='valor',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='data_pagamento',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='pedido',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagamento',
            name='forma',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo_devedor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('cartao', 'Cartão'), ('fiado', 'Fiado')], max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('roupa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.roupa')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.venda')),
            ],
        ),
        migrations.AddField(
            model_name='pagamento',
            name='venda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loja.venda'),
            preserve_default=False,
        ),
    ]
