# Generated by Django 5.1.1 on 2024-09-26 14:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roupa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=7)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('roupa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.roupa')),
            ],
        ),
        migrations.CreateModel(
            name='EstoqueAtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_atual', models.PositiveIntegerField()),
                ('roupa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loja.roupa')),
            ],
        ),
    ]
