# Generated by Django 5.1.1 on 2024-09-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roupa',
            name='numero',
        ),
        migrations.AddField(
            model_name='roupa',
            name='tamanho',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
